#pragma once
/*Stale rysunku*/
float CYLINDER_HEIGHT = 4.0;
float CYLINDER_RADIUS = 0.5;
/*BOARD*/
float BOARD_WIDTH = CYLINDER_RADIUS * 4;
float BOARD_HEIGHT = 0.5;
float BOARD_LENGHT = 6.0;
/*PLANE*/
float PLANE_WIDTH = 10.0f;
float PLANE_HEIGHT = 0.1f;
float PLANE_LENGTH = 15.0f;
/*COLUMN*/
float COLUMN_WIDTH = 1.0f;
float COLUMN_HEIGHT = CYLINDER_HEIGHT/2+ BOARD_HEIGHT;
float COLUMN_LENGTH = 1.0f;
/*TOP*/
float TOP_WIDTH = 10.0f;
float TOP_HEIGHT = COLUMN_LENGTH;
float TOP_LENGTH = COLUMN_LENGTH;


/*ANIMATION*/
int NUMBER_OF_MOVES = BOARD_LENGHT / (CYLINDER_RADIUS * 2);